# Generated by Django 3.1.4 on 2020-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph_plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('x', models.CharField(default='', max_length=30)),
                ('y', models.CharField(default='', max_length=30)),
                ('hue', models.CharField(max_length=30, null=True)),
                ('_html', models.TextField()),
            ],
        ),
    ]
